export const GIST_ACTION_TYPES = {
    SET_GISTS: "SET_GISTS",
    ADD_GIST: "ADD_GIST",
    EDIT_GIST: "EDIT_GIST",
    DELETE_GIST: "DELETE_GIST",
    SEARCH_GIST: "SEARCH_GIST",
};

export const USER_ACTION_TYPES = {
    LOGIN: "SET_USER",
    LOGOUT: "DESTROY_USER",
    CURRENT_USER: "CURRENT_USER"
}

export const AUTH_ACTION_TYPES = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
}

export const FormActionTypes = {
    SET_FILE_NAME: "SET_FILE_NAME",
    SET_DESCRIPTION: "SET_DESCRIPTION",
    SET_CONTENT: "SET_CONTENT",
    SET_HEADING: "SET_HEADING",
}